import { z } from 'zod';

export const Ticker = z.string().regex(/^[A-Z.\-]{1,10}$/);
export type Ticker = z.infer<typeof Ticker>;

export const Quote = z.object({
  symbol: Ticker,
  price: z.number(),
  change: z.number(),
  changePercent: z.number(),
  volume: z.number().int().nonnegative(),
  marketCap: z.number().optional(),
  asOf: z.string(), // ISO
});
export type Quote = z.infer<typeof Quote>;

/**
 * Live ticker quote (issue #81). Distinct from the heavier `Quote` schema
 * above: this is the minimal payload used by the `/api/tickers/:symbol/quote`
 * endpoint and the `useLiveQuote` web hook. `marketState` mirrors
 * yahoo-finance2's upstream values (`REGULAR`, `PRE`, `POST`, `CLOSED`,
 * `PREPRE`, `POSTPOST`).
 */
export const QuoteSchema = z.object({
  symbol: Ticker,
  price: z.number(),
  change: z.number(),
  changePercent: z.number(),
  currency: z.string().min(1),
  marketState: z.enum(['REGULAR', 'PRE', 'POST', 'CLOSED', 'PREPRE', 'POSTPOST']),
  asOf: z.string(), // ISO
  /**
   * Conviction rating (#82). Computed deterministically from the same quote
   * payload (`changePercent` + `volumeRatio` derived from
   * `regularMarketVolume / averageDailyVolume10Day`). Optional so the field
   * can be omitted when upstream data is too thin to be meaningful.
   */
  rating: z
    .object({
      symbol: Ticker,
      rating: z.enum(['SELL', 'HOLD', 'BUY', 'YOLO']),
      score: z.number().min(0).max(100),
      reasons: z.array(z.string()),
      asOf: z.string(),
    })
    .optional(),
});
export type LiveQuote = z.infer<typeof QuoteSchema>;

export const OHLCV = z.object({
  t: z.string(), // ISO date
  o: z.number(),
  h: z.number(),
  l: z.number(),
  c: z.number(),
  v: z.number().int().nonnegative(),
});
export type OHLCV = z.infer<typeof OHLCV>;

export const Indicators = z.object({
  rsi14: z.number().nullable(),
  sma20: z.number().nullable(),
  sma50: z.number().nullable(),
  ema12: z.number().nullable(),
  ema26: z.number().nullable(),
  macd: z.number().nullable(),
  macdSignal: z.number().nullable(),
  atr14: z.number().nullable(),
});
export type Indicators = z.infer<typeof Indicators>;

export const NewsItem = z.object({
  title: z.string(),
  url: z.string().url(),
  source: z.string(),
  publishedAt: z.string(),
  summary: z.string().optional(),
});
export type NewsItem = z.infer<typeof NewsItem>;

export const OptionContract = z.object({
  symbol: z.string(),
  underlying: Ticker,
  expiry: z.string(),
  strike: z.number(),
  type: z.enum(['call', 'put']),
  bid: z.number().nullable(),
  ask: z.number().nullable(),
  last: z.number().nullable(),
  volume: z.number().int().nonnegative().nullable(),
  openInterest: z.number().int().nonnegative().nullable(),
  iv: z.number().nullable(),
  delta: z.number().nullable().optional(),
  gamma: z.number().nullable().optional(),
  theta: z.number().nullable().optional(),
  vega: z.number().nullable().optional(),
});
export type OptionContract = z.infer<typeof OptionContract>;

export const TradePlanLeg = z.object({
  action: z.enum(['buy', 'sell']),
  qty: z.number().int().positive(),
  contract: OptionContract,
});
/**
 * Payoff-at-expiry series for a TradePlan. Generated by
 * `core/src/options/risk-graph.ts` (issue #76). Consumed by the dashboard
 * payoff chart and by `RiskOfficer` for deterministic `maxLoss` enforcement.
 */
export const RiskGraphSeries = z.object({
  underlying: z.array(z.number()),
  pnl: z.array(z.number()),
  breakevens: z.array(z.number()),
  /** null = unbounded loss (e.g. naked short call). */
  maxLoss: z.number().nullable(),
  /** null = unbounded gain (e.g. long call). */
  maxGain: z.number().nullable(),
  /** Positive = net debit, negative = net credit, in dollars. */
  netDebit: z.number(),
});
export type RiskGraphSeries = z.infer<typeof RiskGraphSeries>;

/**
 * Spec-shaped result of `computeRiskGraph` (issue #127). Mirrors
 * `RiskGraphSeries` semantically but with the field names called out in the
 * acceptance criteria (`points`, `breakEvens`, `maxProfit`, `maxLoss`).
 * Validated at the wire/storage boundary; in-process callers can use the
 * `ComputeRiskGraphResult` TS interface directly.
 */
export const RiskGraphResult = z.object({
  points: z.array(
    z.object({
      underlying: z.number(),
      pnl: z.number(),
    }),
  ),
  breakEvens: z.array(z.number()),
  /** null = unbounded gain. */
  maxProfit: z.number().nullable(),
  /** null = unbounded loss. */
  maxLoss: z.number().nullable(),
  netDebit: z.number(),
});
export type RiskGraphResult = z.infer<typeof RiskGraphResult>;

export const RiskReview = z.object({
  ok: z.boolean(),
  violations: z.array(z.string()),
});
export type RiskReview = z.infer<typeof RiskReview>;

export const TradePlan = z.object({
  name: z.string(),
  thesis: z.string(),
  legs: z.array(TradePlanLeg),
  maxLoss: z.number(),
  maxGain: z.number().nullable(), // null = unbounded
  breakEvens: z.array(z.number()),
  notes: z.string().optional(),
  /**
   * Deterministic risk-graph series computed from the legs via Black-Scholes-
   * adjacent math (issue #76). Optional so legacy callers / LLM-only plans
   * keep working until they wire through `OptionsStrategist`.
   */
  riskGraph: RiskGraphSeries.optional(),
});
export type TradePlan = z.infer<typeof TradePlan>;

/**
 * Wire format for `POST /plans` (issue #115). Each candidate plan is paired
 * with its `RiskOfficer` review so user-facing surfaces can flag
 * cap-violating plans instead of silently rendering them. When every
 * candidate fails review, `noCompliantPlans` is set so the surface can
 * render a single "no plans within your configured caps" hint instead of
 * a wall of red.
 */
export const ReviewedTradePlan = z.object({
  plan: TradePlan,
  review: RiskReview,
});
export type ReviewedTradePlan = z.infer<typeof ReviewedTradePlan>;

export const PlansResponse = z.object({
  plans: z.array(ReviewedTradePlan),
  noCompliantPlans: z.boolean().optional(),
});
export type PlansResponse = z.infer<typeof PlansResponse>;

export const TickerProfile = z.object({
  symbol: Ticker,
  name: z.string().min(1),
  exchange: z.string().min(1),
  sector: z.string().min(1),
  industry: z.string().min(1),
  description: z.string().min(1),
  sources: z.array(z.string().url()).min(1),
  validatedAt: z.string(), // ISO
});
export type TickerProfile = z.infer<typeof TickerProfile>;

/** What the LLM is asked to return; sources are added by the agent. */
export const TickerProfileExtraction = z.object({
  symbol: z.string().min(1).max(10),
  name: z.string().min(1),
  exchange: z.string().min(1),
  sector: z.string().min(1),
  industry: z.string().min(1),
  description: z.string().min(1),
});
export type TickerProfileExtraction = z.infer<typeof TickerProfileExtraction>;

export const TickerSuggestion = z.object({
  symbol: z.string(),
  name: z.string().optional(),
  reason: z.string().optional(),
});
export type TickerSuggestion = z.infer<typeof TickerSuggestion>;

export const WatchlistEntry = z.object({
  profile: TickerProfile,
  addedAt: z.string(), // ISO
});
export type WatchlistEntry = z.infer<typeof WatchlistEntry>;

export const ValidationOk = z.object({
  ok: z.literal(true),
  profile: TickerProfile,
  cached: z.boolean().default(false),
});
export const ValidationErr = z.object({
  ok: z.literal(false),
  symbol: z.string(),
  error: z.string(),
  suggestions: z.array(TickerSuggestion).default([]),
});
export const ValidationResult = z.discriminatedUnion('ok', [ValidationOk, ValidationErr]);
export type ValidationResult = z.infer<typeof ValidationResult>;

/**
 * Output of an optional `Technician` agent slot in the briefing pipeline
 * (issue #126; full Technician agent is #74). Kept loose-schema here so a
 * future PR can swap in the real Technician payload without churning the
 * briefing surface.
 */
export const BriefingTechnical = z.object({
  trend: z.string().min(1),
  momentum: z.string().min(1),
  volatility: z.string().min(1),
  keyLevels: z.array(z.number()).default([]),
  commentary: z.string().min(1),
  sourcesUsed: z.array(z.string()).default([]),
});
export type BriefingTechnical = z.infer<typeof BriefingTechnical>;

/**
 * Output of an optional `NewsScout` agent slot (issue #126; full NewsScout
 * agent is #75). Same rationale as `BriefingTechnical`.
 */
export const BriefingNews = z.object({
  headlines: z.array(NewsItem),
  summary: z.string().min(1),
  sourcesUsed: z.array(z.string()).default([]),
});
export type BriefingNews = z.infer<typeof BriefingNews>;

/**
 * Aggregated options-strategist section produced when a caller supplies a
 * thesis + max-loss budget to `Orchestrator.briefing`. Each candidate has
 * already passed through `RiskOfficer.review` so surfaces never render an
 * un-vetted plan.
 */
export const BriefingStrategist = z.object({
  thesis: z.string().min(1),
  candidates: z.array(ReviewedTradePlan),
  noCompliantPlans: z.boolean().default(false),
});
export type BriefingStrategist = z.infer<typeof BriefingStrategist>;

export const Briefing = z.object({
  symbol: Ticker,
  asOf: z.string(),
  quote: Quote,
  indicators: Indicators,
  bullCase: z.string(),
  bearCase: z.string(),
  catalysts: z.array(z.string()),
  risks: z.array(z.string()),
  news: z.array(NewsItem),
  disclaimer: z.string(),
  /**
   * Optional Technician section. Populated when an Orchestrator was
   * constructed with a `technician` agent (issue #126). Absent otherwise so
   * existing CLI/web consumers keep working unchanged.
   */
  ta: BriefingTechnical.optional(),
  /**
   * Optional NewsScout section. Populated when an Orchestrator was
   * constructed with a `newsScout` agent.
   */
  newsScout: BriefingNews.optional(),
  /**
   * Optional strategist section. Populated only when the briefing call
   * includes a `thesis` + `maxLossUsd` budget so the strategist can produce
   * candidate structures.
   */
  strategist: BriefingStrategist.optional(),
  /**
   * Aggregated `RiskOfficer` verdict for the briefing as a whole. When a
   * strategist section is present and *any* candidate fails review, `ok` is
   * false and `violations` summarises why. When there is no strategist
   * section (briefing-only call) this is omitted.
   */
  riskVerdict: RiskReview.optional(),
  /**
   * Flat list of source labels used to assemble this briefing (market data,
   * indicator inputs, agent sources). Mirrors the AGENTS.md "sources used"
   * requirement. Empty by default so existing fixtures don't have to be
   * regenerated.
   */
  sourcesUsed: z.array(z.string()).default([]),
});
export type Briefing = z.infer<typeof Briefing>;
